package pojo;
// Generated Oct 21, 2020 2:10:12 PM by Hibernate Tools 4.3.1

import DAO.DAOTransaksi;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;

/**
 *
 * @author Lenovo
 */
@ManagedBean

/**
 * DataTransaksi generated by hbm2java
 */
public class DataTransaksi implements java.io.Serializable {

    private int idTransaksi;
    private String namaLengkap;
    private String alamatLengkap;
    private String email;
    private String noTelp;
    private String kodeBarang;
    private String jnsPembayaran;
    private String jnsPengiriman;
    private String ukuran;
    private int jumlah;

    /**
     *
     */
    public DataTransaksi() {
    }

    /**
     *
     * @param idTransaksi
     * @param namaLengkap
     * @param alamatLengkap
     * @param email
     * @param noTelp
     * @param kodeBarang
     * @param jnsPembayaran
     * @param jnsPengiriman
     * @param ukuran
     * @param jumlah
     */
    public DataTransaksi(int idTransaksi, String namaLengkap, String alamatLengkap, String email, String noTelp, String kodeBarang, String jnsPembayaran, String jnsPengiriman, String ukuran, int jumlah) {
        this.idTransaksi = idTransaksi;
        this.namaLengkap = namaLengkap;
        this.alamatLengkap = alamatLengkap;
        this.email = email;
        this.noTelp = noTelp;
        this.kodeBarang = kodeBarang;
        this.jnsPembayaran = jnsPembayaran;
        this.jnsPengiriman = jnsPengiriman;
        this.ukuran = ukuran;
        this.jumlah = jumlah;
    }

    /**
     *
     * @return
     */
    public int getIdTransaksi() {
        return this.idTransaksi;
    }

    /**
     *
     * @param idTransaksi
     */
    public void setIdTransaksi(int idTransaksi) {
        this.idTransaksi = idTransaksi;
    }

    /**
     *
     * @return
     */
    public String getNamaLengkap() {
        return this.namaLengkap;
    }

    /**
     *
     * @param namaLengkap
     */
    public void setNamaLengkap(String namaLengkap) {
        this.namaLengkap = namaLengkap;
    }

    /**
     *
     * @return
     */
    public String getAlamatLengkap() {
        return this.alamatLengkap;
    }

    /**
     *
     * @param alamatLengkap
     */
    public void setAlamatLengkap(String alamatLengkap) {
        this.alamatLengkap = alamatLengkap;
    }

    /**
     *
     * @return
     */
    public String getEmail() {
        return this.email;
    }

    /**
     *
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     *
     * @return
     */
    public String getNoTelp() {
        return this.noTelp;
    }

    /**
     *
     * @param noTelp
     */
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }

    /**
     *
     * @return
     */
    public String getKodeBarang() {
        return this.kodeBarang;
    }

    /**
     *
     * @param kodeBarang
     */
    public void setKodeBarang(String kodeBarang) {
        this.kodeBarang = kodeBarang;
    }

    /**
     *
     * @return
     */
    public String getJnsPembayaran() {
        return this.jnsPembayaran;
    }

    /**
     *
     * @param jnsPembayaran
     */
    public void setJnsPembayaran(String jnsPembayaran) {
        this.jnsPembayaran = jnsPembayaran;
    }

    /**
     *
     * @return
     */
    public String getJnsPengiriman() {
        return this.jnsPengiriman;
    }

    /**
     *
     * @param jnsPengiriman
     */
    public void setJnsPengiriman(String jnsPengiriman) {
        this.jnsPengiriman = jnsPengiriman;
    }

    /**
     *
     * @return
     */
    public String getUkuran() {
        return this.ukuran;
    }

    /**
     *
     * @param ukuran
     */
    public void setUkuran(String ukuran) {
        this.ukuran = ukuran;
    }

    /**
     *
     * @return
     */
    public int getJumlah() {
        return this.jumlah;
    }

    /**
     *
     * @param jumlah
     */
    public void setJumlah(int jumlah) {
        this.jumlah = jumlah;
    }

    

    public String getbyid() {
        DAOTransaksi tra = new DAOTransaksi();
        List<DataTransaksi> lTra = tra.getbyID(String.valueOf(idTransaksi));
        namaLengkap = lTra.get(0).namaLengkap;
        alamatLengkap = lTra.get(0).alamatLengkap;
        email = lTra.get(0).email;
        noTelp = lTra.get(0).noTelp;
        kodeBarang = lTra.get(0).kodeBarang;
        jnsPembayaran = lTra.get(0).jnsPembayaran;
        jnsPengiriman = lTra.get(0).jnsPengiriman;
        ukuran = lTra.get(0).ukuran;
        return "Invoice";
    }

    //SHOW ALL DATA//
    public List<DataTransaksi> getall()
    {
        DAOTransaksi pdao=new DAOTransaksi();
        List<DataTransaksi> prod=pdao.retrieveProduk();
        return prod;
    }
    //UPDATE DATA
    public String update()
    {
        DAOTransaksi pdao=new DAOTransaksi();
        pdao.updateProduk(this);
        return "view_admin";
    }
    //INSERT DATA 
    public String save() {
        DAOTransaksi tra = new DAOTransaksi();
        tra.addProduk(this);
        return "invoice";
    }
    
    //DELETE DATA
    public String delete()
    {    
        DAOTransaksi pdao=new DAOTransaksi();
        pdao.deleteTransaksi(idTransaksi);
        return "view_admin";
    }

}
