package pojo;
// Generated Oct 21, 2020 2:10:12 PM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;
@ManagedBean




/**
 * DataAdmin generated by hbm2java
 */
public class DataAdmin  implements java.io.Serializable {


     private Integer idAdmin;
     private String username;
     private String password;
     private String role;
     
     public String validasiLogin(){
        DAOLogin uDao = new DAOLogin();
        List<DataAdmin> us = uDao.getBy(username, password);
        if (us != null){
            username = us.get(0).username;
            password = us.get(0).password;
            role = us.get(0).role;
            return "view_admin";
        }
        return "error";
    }

    public DataAdmin() {
    }

    public DataAdmin(String username, String password, String role) {
       this.username = username;
       this.password = password;
       this.role = role;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


